<template>
  <div>
    <scroll class="content" :probeType="2">
      <ul>
        <li>个人1</li>
        <li>个人2</li>
        <li>个人3</li>
        <li>个人4</li>
        <li>个人5</li>
        <li>个人6</li>
        <li>个人7</li>
        <li>个人8</li>
        <li>个人9</li>
        <li>个人10</li>
        <li>个人11</li>
        <li>个人12</li>
        <li>个人13</li>
        <li>个人14</li>
        <li>个人15</li>
        <li>个人16</li>
        <li>个人17</li>
        <li>个人18</li>
        <li>个人19</li>
        <li>个人20</li>
        <li>个人21</li>
        <li>个人22</li>
        <li>个人23</li>
        <li>个人24</li>
        <li>个人25</li>
        <li>个人26</li>
        <li>个人27</li>
        <li>个人28</li>
        <li>个人29</li>
        <li>个人30</li>
        <li>个人31</li>
        <li>个人32</li>
        <li>个人33</li>
        <li>个人34</li>
        <li>个人35</li>
        <li>个人36</li>
        <li>个人37</li>
        <li>个人38</li>
        <li>个人39</li>
        <li>个人40</li>
        <li>个人41</li>
        <li>个人42</li>
        <li>个人43</li>
        <li>个人44</li>
        <li>个人45</li>
        <li>个人46</li>
        <li>个人47</li>
        <li>个人48</li>
        <li>个人49</li>
        <li>个人50</li>
        <li>个人51</li>
        <li>个人52</li>
        <li>个人53</li>
        <li>个人54</li>
        <li>个人55</li>
        <li>个人56</li>
        <li>个人57</li>
        <li>个人58</li>
        <li>个人59</li>
        <li>个人60</li>
        <li>个人61</li>
        <li>个人62</li>
        <li>个人63</li>
        <li>个人64</li>
        <li>个人65</li>
        <li>个人66</li>
        <li>个人67</li>
        <li>个人68</li>
        <li>个人69</li>
        <li>个人70</li>
        <li>个人71</li>
        <li>个人72</li>
        <li>个人73</li>
        <li>个人74</li>
        <li>个人75</li>
        <li>个人76</li>
        <li>个人77</li>
        <li>个人78</li>
        <li>个人79</li>
        <li>个人80</li>
        <li>个人81</li>
        <li>个人82</li>
        <li>个人83</li>
        <li>个人84</li>
        <li>个人85</li>
        <li>个人86</li>
        <li>个人87</li>
        <li>个人88</li>
        <li>个人89</li>
        <li>个人90</li>
        <li>个人91</li>
        <li>个人92</li>
        <li>个人93</li>
        <li>个人94</li>
        <li>个人95</li>
        <li>个人96</li>
        <li>个人97</li>
        <li>个人98</li>
        <li>个人99</li>
        <li>个人100</li>
      </ul>
    </scroll>
  </div>
</template>

<script>
import scroll from '../../components/common/scroll/scroll'

export default {
  name:'profile',
  components:{
    scroll,
  }
}
</script>

<style scoped>
.content{
  height: 300px;
  background-color: red;
  overflow: hidden;
}
</style>